HouseRentingSystem/Controllers/HomeController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HouseRentingSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHouseService houseService;

        public HomeController(IHouseService _houseService)
        {
            houseService = _houseService;
        }

        public async Task<IActionResult> Index()
        {
            var model = await houseService.LastThreeHouses();

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HouseRentingSystem/Controllers/HouseController.cs
using HouseRentingSystem.Core.Contracts;
using HouseRentingSystem.Core.Models.House;
using HouseRentingSystem.Extensions;
using HouseRentingSystem.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace HouseRentingSystem.Controllers
{
    [Authorize]
    public class HouseController : Controller
    {
        private readonly IHouseService houseService;

        private readonly IAgentService agentService;

        public HouseController(IHouseService _houseService,
                               IAgentService _agentService)
        {
            this.houseService = _houseService;
            this.agentService = _agentService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllHousesQueryModel query)
        {
            var result = await houseService.All(
                 query.Category,
                 query.SearchTerm,
                 query.Sorting,
                 query.CurrentPage,
                 AllHousesQueryModel.HousesPerPage);

            query.TotalHousesCount = result.TotalHouseCount;

            query.Categories = await houseService.AllCategoriesNames();

            query.Houses = result.Houses;

            return View(query);
        }

        public async Task<IActionResult> Mine()
        {
            IEnumerable<HouseServiceModel> myHouses;

            var userId = User.Id();

            if (await agentService.ExistById(userId))
            {
                int agentId = await agentService.GetAgentId(userId);
                myHouses = await houseService.AllHousesByAgentId(agentId);
            }
            else
            {
                myHouses = await houseService.AllHousesByUserId(userId);
            }


            return View(myHouses);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id,string information)
        {
            if ((await houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var model = await houseService.HouseDetailsById(id);
            
            if (information != model.GetInformation())
            {
                TempData["ErrorMessage"] = "Don't touch my slug!";

                return RedirectToAction("Index", "Home");
            }


            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!(await agentService.ExistById(User.Id())))
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            }

            var model = new HouseModel()
            {
                HouseCategories = await houseService.AllCategories()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(HouseModel model)
        {
            if (!(await agentService.ExistById(User.Id())))
            {
                return RedirectToAction(nameof(AgentController.Become), "Agent");
            }

            if (!(await houseService.CategoryExists(model.CategoryId)))
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Categoru does not exist");
            }

            if (!ModelState.IsValid)
            {
                model.HouseCategories = await houseService.AllCategories();

                return View(model);
            }

            int agentId = await agentService.GetAgentId(User.Id());

            int id = await houseService.Create(model, agentId);

            return RedirectToAction(nameof(Details), new { id = id, information = model.GetInformation() });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if ((await houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await houseService.HasAgentWithId(id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var house = await houseService.HouseDetailsById(id);

            var categoryId = await houseService.GetHouseCategoryId(id);

            var model = new HouseModel()
            {
                Id = id,
                Title = house.Title,
                Address = house.Address,
                ImageUrl = house.ImageUrl,
                CategoryId = categoryId,
                Description = house.Description,
                PricePerMonth = house.PricePerMonth,
                HouseCategories = await houseService.AllCategories()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HouseModel model)
        {
            if ((await houseService.Exists(model.Id)) == false)
            {
                ModelState.AddModelError("", "House does not exist!");

                model.HouseCategories = await houseService.AllCategories();

                return View(model);
            }

            if ((await houseService.HasAgentWithId(model.Id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            if ((await houseService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError("", "Category does not exist");

                model.HouseCategories = await houseService.AllCategories();

                return View(model);
            }

            if (ModelState.IsValid == false)
            {
                model.HouseCategories = await houseService.AllCategories();

                return View(model);
            }

            await houseService.Edit(model.Id, model);

            return RedirectToAction(nameof(Details), new { id = model.Id,information = model.GetInformation() });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await houseService.HasAgentWithId(id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            var house = await houseService.HouseDetailsById(id);

            var model = new HouseDetailsViewModel()
            {
                Title = house.Title,
                Address = house.Address,
                ImageUrl = house.ImageUrl
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, HouseDetailsViewModel model)
        {
            if ((await houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await houseService.HasAgentWithId(id, User.Id())) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            await houseService.Delete(id);

            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Rent(int id)
        {
            if ((await houseService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await agentService.ExistById(User.Id())))
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            if (await houseService.IsRented(id))
            {
                return RedirectToAction(nameof(All));
            }

            await houseService.Rent(id, User.Id());

            return RedirectToAction(nameof(Mine));
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            if ((await houseService.Exists(id)) == false || await houseService.IsRented(id) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (await houseService.IsRentedByUserWithId(id, User.Id()) == false)
            {
                return RedirectToPage("/Account/AccessDenied", new { area = "Identity" });
            }

            await houseService.Leave(id);

            return RedirectToAction(nameof(Mine));
        }
    }
}

HouseRentingSystem/Views/Home/Index.cshtml
@model IEnumerable<HouseHomeModel>

@{
    ViewData["Title"] = "Home Page";
    bool first = true;
}


@if (Model.Count() == 0)
{
    <div class="mt-4 p-5 bg-light">
        <h1 class="display-4">Welcome to the best place for renting houses!</h1>
        <p class="lead">
            There are no houses in the system currently availeble,
            so why don't you just add one?
        </p>
        <hr class="my-4">
        <p class="lead">
            @if (this.User?.Identity != null && this.User.Identity.IsAuthenticated)
            {
                <a asp-controller="House" asp-action="Add" class="btn btn-primary btn-lg" role="button">Add House</a>
            }
        </p>
    </div>
}

<div class="mb-5"></div>

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        @foreach (var house in Model)
        {
            <div class="carousel-item @(first ? "active" : string.Empty)">
                <img class="d-block w-100" style="height:500px"
                 src="@house.ImageUrl" alt="@house.Title">
                <div class="carousel-caption d-none d-md-block">
                    <h5>
                        <a class="btn btn-primary" asp-controller="House" asp-action="Details"
                       asp-route-id="@house.Id" asp-route-information="@house.GetInformation()"> @house.Title</a>
                    </h5>
                </div>
            </div>
            @(first = false)
            ;
        }
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="mb-5"></div>
<div class="row">
    <div class="col-12 text-center">
        <button class="btn btn-primary" id="statistics-button">Show Statistics</button>
    </div>
</div>

<div class="mt-4 p-5 bg-light d-none" id="statistics">
    <div class="row">
        <h2 class="col-md-6 text-center" id="total-houses"></h2>
        <h2 class="col-md-6 text-center" id="total-rents"></h2>
    </div>
</div>
@section Scripts {
    <script>
        $('#statistics-button').on('click', ev => {
            $.get('https://localhost:7200/api/StatisticsApi', (data) => {
                $('#total-houses').text(data.totalHouses + "Houses");
                $('#total-rents').text(data.totalRents + " Rents");
                $('#statistics').removeClass('d-none');
                $('#statistics-button').hide();
            });
        });
    </script>
}